# Uncomment the next line to define a global platform for your project
platform :ios, ’10.1’
 # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
# Pods for FAITHMainUIDemo

target 'FAITHMainUIDemo' do
 
pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'MJExtension', '~> 3.0.13'
end
